spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: medlink
    driver-class-name: com.mysql.jdbc.Driver
jpa:
    hibernate:
      ddl-auto: create
    show-sql: true