spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: medlink
    driver-class-name: com.mysql.jdbc.Driver
jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
book: 
  bookName: "springboot开发颠覆者"
  price: 76
  
mybatis:
  config-location: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.forezp.entity
